---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: gogs_pvc.template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: gogs-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
