apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ocp_groups.yml
objects:
- apiVersion: v1
  kind: Group
  metadata:
    creationTimestamp: null
    labels:
      client: alpha
    name: alpha
  users:
  - amy
  - andrew
- apiVersion: v1
  kind: Group
  metadata:
    creationTimestamp: null
    labels:
      client: beta
    name: beta
  users:
  - brian
  - betty
