---
apiVersion: v1
kind: Template
metatdata:
  creationTimestamp: null
  name: jenkins-pvc.template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: jenkins
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10g
