---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: nexus3_pvc.template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: nexus-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
