---
- name: Deploy {{ target }}
  hosts: "{{ target }}"
  vars:
    GUID: { GUID }
    jenkins_namespace: $GUID-jenkins
    CICD_NAMESPACE: $GUID-jenkins
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
