---
- hosts: nfs
  tasks:
    - name: copy create PVs script from bastion to support
      copy:
        path: /root/create_support_pvs.sh
        dest: /root/create_support_pvs.sh
        remote_src: no


- hosts: nfs
  tasks:
    - name: create support PVs
      command: /root/create_support_pvs.sh
      args:
        chdir: /root/
        create: /etc/exports.d/openshift-uservols.exports

- hosts: localhost
  tasks:
    - name: create PVs on bastion host
      command: /root/openshift-advanced-deployment-homework/scripts/create_bastion_pvs.sh
      args:
        chdir: /root/openshift-advanced-deployment-homework/scripts/
        create: /root/pvs
