---
- hosts: support1
  tasks:
    - name: copy create PVs script from bastion to support
      copy:
        path: /root/openshift-advanced-deployment-homework/scripts/create_support_pvs.sh
        dest: /root/openshift-advanced-deployment-homework/scripts/create_support_pvs.sh
        remote_src: no
        line: 'network-polciy: redhat/openshift-ovs-multitenant'

- hosts: support1
  tasks:
    - name: create support PVs
      command: /root/openshift-advanced-deployment-homework/scripts/create_support_pvs.sh
      args:
        chdir: /root/openshift-advanced-deployment-homework/scripts/

- hosts: localhost
  tasks:
    - name: create PVs on bastion host
      command: /root/openshift-advanced-deployment-homework/scripts/create_bastion_pvs.sh
      args:
        chdir: /root/openshift-advanced-deployment-homework/scripts/
