---
ansible_connection: local
openshift_cluster_content:
- object: jenkins
  content:
  - name: "jenkins"
    namespace: "{{ jenkins_namespace }}"
    template: "{{ playbook_dir }}/templates/jenkins.yml"
    params: "{{ playbook_dir }}/inventory/params/jenkins"
    tags:
    - jenkins
