---
ansible_connection: local
openshift_cluster_content:
- object: sonarqube
  content:
  - name: "sonarqube"
    namespace: "{{ sonarqube_namespace }}"
    template: "{{ playbook_dir }}/templates/sonarqube.yml"
    params: "{{ playbook_dir }}/inventory/params/sonarqube"
    tags:
    - sonarqube
